-- =========================================================================
-- HardwareHub Supabase SQL DDL Schema
-- =========================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ── 1. PROFILES TABLE ────────────────────────────────────────────────────
-- Extends Supabase auth.users with custom fields and roles
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  role text not null check (role in ('admin', 'manager', 'staff')),
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- ── 2. CATEGORIES TABLE ──────────────────────────────────────────────────
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;

-- ── 3. SUPPLIERS TABLE ───────────────────────────────────────────────────
create table public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.suppliers enable row level security;

-- ── 4. CUSTOMERS TABLE ───────────────────────────────────────────────────
create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.customers enable row level security;

-- ── 5. PRODUCTS TABLE ────────────────────────────────────────────────────
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references public.categories(id) on delete restrict not null,
  sku text not null unique,
  unit_price numeric(12,2) not null check (unit_price >= 0),       -- Selling Price
  buying_price numeric(12,2) not null check (buying_price >= 0),   -- Cost Price
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  reorder_level integer not null default 5 check (reorder_level >= 0),
  supplier_id bigint references public.suppliers(id) on delete set null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.products enable row level security;

-- ── 6. PURCHASES TABLE ───────────────────────────────────────────────────
create table public.purchases (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete restrict not null,
  purchase_date date default current_date not null,
  total_cost numeric(12,2) not null default 0.00 check (total_cost >= 0),
  payment_status text not null check (payment_status in ('Paid', 'Credit', 'Partial')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.purchases enable row level security;

-- ── 7. PURCHASE ITEMS TABLE ──────────────────────────────────────────────
create table public.purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint references public.purchases(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete restrict not null,
  quantity integer not null check (quantity > 0),
  buying_price numeric(12,2) not null check (buying_price >= 0),
  subtotal numeric(12,2) generated always as (quantity * buying_price) stored
);

alter table public.purchase_items enable row level security;

-- ── 8. SALES TABLE ───────────────────────────────────────────────────────
create table public.sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete restrict not null,
  sale_date date default current_date not null,
  total_amount numeric(12,2) not null default 0.00 check (total_amount >= 0),
  payment_status text not null check (payment_status in ('Paid', 'Credit', 'Partial')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.sales enable row level security;

-- ── 9. SALE ITEMS TABLE ──────────────────────────────────────────────────
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete restrict not null,
  quantity integer not null check (quantity > 0),
  selling_price numeric(12,2) not null check (selling_price >= 0),
  subtotal numeric(12,2) generated always as (quantity * selling_price) stored
);

alter table public.sale_items enable row level security;

-- ── 10. TRANSPORTATION TABLE ──────────────────────────────────────────────
create table public.transportation (
  id bigint generated by default as identity primary key,
  related_type text not null check (related_type in ('Purchase', 'Sale')),
  related_id bigint not null, -- references purchases.id or sales.id
  vehicle_name text not null,
  driver_name text not null,
  source text not null,
  destination text not null,
  dispatch_date date not null,
  delivery_date date,
  transport_cost numeric(12,2) not null default 0.00 check (transport_cost >= 0),
  status text not null default 'Dispatched' check (status in ('Dispatched', 'In Transit', 'Delivered', 'Returned')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.transportation enable row level security;

-- ── 11. EXPENSES TABLE ───────────────────────────────────────────────────
create table public.expenses (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Rent', 'Utilities', 'Transport', 'Salaries', 'Marketing', 'Other')),
  amount numeric(12,2) not null check (amount >= 0),
  date date default current_date not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.expenses enable row level security;


-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES DEFINITIONS
-- =========================================================================

-- Helper function to fetch the role of the logged in user
create or replace function public.get_auth_role()
returns text as $$
  select role from public.profiles where id = auth.uid();
$$ language sql security definer;

-- ── Policies for Profiles ────────────────────────────────────────────────
create policy "Allow all users to view profiles"
  on public.profiles for select
  using (auth.uid() is not null);

create policy "Allow admins to update profiles"
  on public.profiles for all
  using (public.get_auth_role() = 'admin');

create policy "Allow users to edit their own profile details"
  on public.profiles for update
  using (auth.uid() = id);

-- ── Policies for Categories ─────────────────────────────────────────────
create policy "Allow everyone to read categories"
  on public.categories for select
  using (auth.uid() is not null);

create policy "Allow admins and managers to modify categories"
  on public.categories for all
  using (public.get_auth_role() in ('admin', 'manager'));

-- ── Policies for Suppliers & Customers ───────────────────────────────────
create policy "Allow everyone to read contacts"
  on public.suppliers for select using (auth.uid() is not null);
create policy "Allow everyone to read customers"
  on public.customers for select using (auth.uid() is not null);

create policy "Allow admins and managers to write suppliers"
  on public.suppliers for all using (public.get_auth_role() in ('admin', 'manager'));
create policy "Allow admins and managers to write customers"
  on public.customers for all using (public.get_auth_role() in ('admin', 'manager'));

create policy "Allow staff to write customers"
  on public.customers for insert using (public.get_auth_role() = 'staff');

-- ── Policies for Products ───────────────────────────────────────────────
create policy "Allow all logged in users to read products"
  on public.products for select
  using (auth.uid() is not null);

create policy "Allow admins and managers to manage products"
  on public.products for all
  using (public.get_auth_role() in ('admin', 'manager'));

-- ── Policies for Purchases & Purchase Items ──────────────────────────────
create policy "Allow everyone to select purchases"
  on public.purchases for select using (auth.uid() is not null);
create policy "Allow everyone to select purchase items"
  on public.purchase_items for select using (auth.uid() is not null);

create policy "Allow admins and managers to manage purchases"
  on public.purchases for all using (public.get_auth_role() in ('admin', 'manager'));
create policy "Allow admins and managers to manage purchase items"
  on public.purchase_items for all using (public.get_auth_role() in ('admin', 'manager'));

-- ── Policies for Sales & Sale Items ──────────────────────────────────────
create policy "Allow everyone to select sales"
  on public.sales for select using (auth.uid() is not null);
create policy "Allow everyone to select sale items"
  on public.sale_items for select using (auth.uid() is not null);

create policy "Allow authenticated users to insert sales"
  on public.sales for insert with check (auth.uid() is not null);
create policy "Allow authenticated users to insert sale items"
  on public.sale_items for insert with check (auth.uid() is not null);

create policy "Allow admins and managers to edit sales"
  on public.sales for all using (public.get_auth_role() in ('admin', 'manager'));
create policy "Allow admins and managers to edit sale items"
  on public.sale_items for all using (public.get_auth_role() in ('admin', 'manager'));

-- ── Policies for Transportation ──────────────────────────────────────────
create policy "Allow everyone to read transportation logs"
  on public.transportation for select using (auth.uid() is not null);

create policy "Allow admins and managers to manage transportation"
  on public.transportation for all using (public.get_auth_role() in ('admin', 'manager'));

create policy "Allow staff to update transport status"
  on public.transportation for update using (public.get_auth_role() = 'staff')
  with check (public.get_auth_role() = 'staff');

-- ── Policies for Expenses ────────────────────────────────────────────────
create policy "Allow admins and managers to read expenses"
  on public.expenses for select using (public.get_auth_role() in ('admin', 'manager'));

create policy "Allow admins and managers to manage expenses"
  on public.expenses for all using (public.get_auth_role() in ('admin', 'manager'));
